### ISSUE TITLE
markerTags ceased working – maybe due to YAML parsing the code block?

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#135]
Some time ago I last tried `markerTags`, so I can’t say since which version it fails.

I know I have a few, and Obsidian search also finds these when searching for `tag:#family`, but maps doesn’t, anymore. I _suspect_ it may have to do with YAML parsing the code block, since `#` introduces a _comment_.

Here are the variants I tried (on my main map):

```yaml
markerTags: #family
markerTags: family
markerTags: "#family"
markerTags: "family"
markerTags: [#family] # <-- this errors out
markerTags: [family]
markerTags: ["#family"]
markerTags: ["family"]
```

Closed and reopened note every time, to be sure.
