### ISSUE TITLE
Can you make the map on the left side

### ISSUE THREAD

**Issue by zhl111** [valentine195/obsidian-leaflet-plugin#265]
![image](https://user-images.githubusercontent.com/29135984/146637362-c987629e-7edb-4bb0-bd61-879d281a4ab0.png)

**Comment by valentine195** [comment]
You can do this with a css snippet:

```css
.block-languange-leaflet {
   margin-left: 0;
}
```
