### ISSUE TITLE
Image Map Specification Logic

### ISSUE THREAD

**Issue by Servinjesus1** [valentine195/obsidian-leaflet-plugin#278]
I'm confused by the logic for fully specifying an image map. I get this plugin was made with real maps in mind, but the latitude/longitude logic seems to not play well with images.

Here's my MWE (MVP? my template, so to speak) for an image map:

```yaml
id: image-map
image: image.svg
bounds: # Staple image to canvas
    - [ 0, 0 ]
    - [ 100, 100 ]

# Set Zoom bounds (needs stapling above)
minZoom: 3
maxZoom: 7
defaultZoom: 1

# Set coordinate system
unit: feet
scale: 1
lat: 50%
long: 50%

# Additional Features
darkMode: true
```

So, I'm curious:
1. Where should `(0,0)` be? At the bottom left corner of the image?
2. What do the `bounds` specify, particularly in relation to the coordinates (or "canvas")? I know they're % from top-left corner (no `%` though), and if not as above, they should skew the image. Should this skew work with `svg`s?
3. Why no `%` in `bounds` but needed in `lat`/`long` (c.f. #138 )?
4. Why is enforcing `bounds` required (e.g. #272)? It's currently necessary for `Zoom` to work correctly. Might I suggest making the image size in pixels (or for `svg`s the "nominal size" in pixels) the default value for `bounds` and making the `Zoom` and `scale` parameters play well with this (so scale is in units of `unit`/`pixel` rather than `unit`/`image-size`, and maybe `Zoom` is in units of `pixels`/`leaflet-size`)? I think then images would feel a lot more like "maps" (or engineering drawings, if you're familiar with those), when necessary, and also like a basic image if not.

I just tried to make an image map [with this `svg` specifically](https://upload.wikimedia.org/wikipedia/commons/3/37/ANSI_Keyboard_Layout_Diagram_with_Form_Factor.svg), and the origin looks like it's way below the bottom left corner of the image, which spurred my questions above.
